/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'M55_HP.Release+Alif-AppKit-E7' 
 * Target:  'Release+Alif-AppKit-E7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HP.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* AlifSemiconductor::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO0   1           /* Driver GPIO0 */
/* AlifSemiconductor::CMSIS Driver:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* Keil::CMSIS Driver:VIO:Board&AppKit-E7-AIML@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_APPKIT_E7_AIML


#endif /* RTE_COMPONENTS_H */
